export interface DepthIndexEnvConfig {
  // Cloud API (set on server/deployment platform)
  VITE_DEPTHINDEX_CLOUD_PROVIDER?: 'openai' | 'gemini' | 'anthropic';
  VITE_DEPTHINDEX_CLOUD_API_KEY?: string;
  VITE_DEPTHINDEX_CLOUD_MODEL?: string;
  VITE_DEPTHINDEX_CLOUD_ENDPOINT?: string; // Custom endpoint
  
  // Error Reporting
  VITE_DEPTHINDEX_ERROR_REPORT_TARGET?: 'github' | 'email' | 'custom' | 'none';
  VITE_DEPTHINDEX_ERROR_REPORT_REPO?: string;
  VITE_DEPTHINDEX_ERROR_REPORT_EMAIL?: string;
  VITE_DEPTHINDEX_ERROR_REPORT_ENDPOINT?: string;
  
  // Features
  VITE_DEPTHINDEX_DEFAULT_MODE?: 'on-device' | 'hybrid' | 'cloud';
  VITE_DEPTHINDEX_ALLOW_CLOUD_CONFIG?: 'true' | 'false'; // Show/hide cloud config UI
  VITE_DEPTHINDEX_PWA_ENABLED?: 'true' | 'false';
  
  // Branding
  VITE_DEPTHINDEX_PANEL_TITLE?: string;
  VITE_DEPTHINDEX_POWERED_BY_TEXT?: string;
  VITE_DEPTHINDEX_POWERED_BY_URL?: string;
}

export function loadEnvConfig(): Partial<DepthIndexEnvConfig> {
  if (typeof window === 'undefined') return {};

  const metaEnv = (import.meta as any).env || {};

  return {
    VITE_DEPTHINDEX_CLOUD_PROVIDER: metaEnv.VITE_DEPTHINDEX_CLOUD_PROVIDER,
    VITE_DEPTHINDEX_CLOUD_API_KEY: metaEnv.VITE_DEPTHINDEX_CLOUD_API_KEY,
    VITE_DEPTHINDEX_CLOUD_MODEL: metaEnv.VITE_DEPTHINDEX_CLOUD_MODEL,
    VITE_DEPTHINDEX_CLOUD_ENDPOINT: metaEnv.VITE_DEPTHINDEX_CLOUD_ENDPOINT,
    VITE_DEPTHINDEX_ERROR_REPORT_TARGET: metaEnv.VITE_DEPTHINDEX_ERROR_REPORT_TARGET,
    VITE_DEPTHINDEX_ERROR_REPORT_REPO: metaEnv.VITE_DEPTHINDEX_ERROR_REPORT_REPO,
    VITE_DEPTHINDEX_ERROR_REPORT_EMAIL: metaEnv.VITE_DEPTHINDEX_ERROR_REPORT_EMAIL,
    VITE_DEPTHINDEX_ERROR_REPORT_ENDPOINT: metaEnv.VITE_DEPTHINDEX_ERROR_REPORT_ENDPOINT,
    VITE_DEPTHINDEX_DEFAULT_MODE: metaEnv.VITE_DEPTHINDEX_DEFAULT_MODE,
    VITE_DEPTHINDEX_ALLOW_CLOUD_CONFIG: metaEnv.VITE_DEPTHINDEX_ALLOW_CLOUD_CONFIG,
    VITE_DEPTHINDEX_PWA_ENABLED: metaEnv.VITE_DEPTHINDEX_PWA_ENABLED,
    VITE_DEPTHINDEX_PANEL_TITLE: metaEnv.VITE_DEPTHINDEX_PANEL_TITLE,
    VITE_DEPTHINDEX_POWERED_BY_TEXT: metaEnv.VITE_DEPTHINDEX_POWERED_BY_TEXT,
    VITE_DEPTHINDEX_POWERED_BY_URL: metaEnv.VITE_DEPTHINDEX_POWERED_BY_URL,
  };
}
